name: Node.js CI/CD with Docker

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Atualize para a versão do Node.js que você está usando

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg NODE_ENV=production \
          --build-arg DB_HOST=$DB_HOST \  
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          -t bernhoeft/teste:1.0 .

    - name: Push Docker Image to Registry
      run: |
        docker push bernhoeft/teste:1.0